name: Attach APK to release
on:
  release:
    types: [published]
  workflow_dispatch:
  pull_request:

jobs:
  build_apk:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

    steps:
      - name: Download artifact from last successful run on main
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build-on-merge-workflow.yml
          workflow_conclusion: success
          branch: main
          name: latest-build
          path: ./artifacts # will create the path if it doesn't exist

      - name: Sanity Check
        run: ls ./artifacts # list for sanity

      - name: Rename APK
        run: mv ./artifacts/latest-build.apk ./app-${{ github.event.release.tag_name }}.apk
      - name: Sign APK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          sudo apt-get install -y zipalign apksigner
          
          echo "${ANDROID_KEYSTORE_BASE64}" | base64 --decode > release.keystore

          # Sign the APK
          apksigner sign \
            --ks release.keystore \
            --ks-key-alias "$ANDROID_KEY_ALIAS" \
            --ks-pass "pass:$ANDROID_KEYSTORE_PASSWORD" \
            --key-pass "pass:$ANDROID_KEY_PASSWORD" \
            --out signed-${{ github.event.release.tag_name }}.apk \
              app-${{ github.event.release.tag_name }}.apk
          apksigner verify --verbose signed-${{ github.event.release.tag_name }}.apk
          rm release.keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          name: app-release-${{ github.event.release.tag_name }}
          files: signed-${{ github.event.release.tag_name }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}