name: run-tests.yml
on:
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 23
          cache: 'gradle'

      - name: Install firebase-tools
        run: npm install -g firebase-tools

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: SANITY CHECK
        run: ls /usr/local/lib/android/sdk

      - name: Add Emulator to Path
        run: |
          export $PATH:/usr/local/lib/android/sdk/emulator

      - name: Initialize android emulator
        env:
          AVD_NAME: "TestAVD"
          API_LEVEL: 36
        run: | 
          chmod +x ./scripts/create-android-emu.sh
          ./scripts/create-android-emu.sh

      - name: Start the Android Emulator
        run: emulator -avd TestAVD

