name: run-tests.yml
on:
  pull_request:

jobs:

  run_tests:
    runs-on: ubuntu-latest
    env:
      ANDROID_USER_HOME: ${{ github.workspace }}/.android
      ANDROID_AVD_HOME: ${{ github.workspace }}/.android/avd
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 23
          cache: 'gradle'

      - name: Install Emulator Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpulse0 libgl1

      - name: Decode google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_BASE64 }}" | base64 --decode > app/google-services.json

      - name: Install firebase-tools
        run: npm install -g firebase-tools

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Add Emulator to Path
        run: |
          export PATH=$PATH:/usr/local/lib/android/sdk/emulator
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 36
          target: google_apis
          arch: x86_64
          disable-animations: 'true'
          force-avd-creation: true
          emulator-options: >
            '-no-window 
            -gpu swiftshader_indirect 
            -no-snapshot 
            -noaudio 
            -no-boot-anim'
          script: |
            firebase emulators:exec --project ${{ secrets.FIREBASE_PROJECT_ID }} "./gradlew connectedAndroidTest"

