name: run-tests.yml
on:
  pull_request:

jobs:

  run_tests:
    runs-on: ubuntu-latest
    env:
      ANDROID_USER_HOME: ${{ github.workspace }}/.android
      ANDROID_AVD_HOME: ${{ github.workspace }}/.android/avd
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 23
          cache: 'gradle'

      - name: Install Emulator Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpulse0 libgl1

      - name: Decode google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_BASE64 }}" | base64 --decode > app/google-services.json

      - name: Install firebase-tools
        run: npm install -g firebase-tools

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: SANITY CHECK
        run: ls /usr/local/lib/android/sdk/emulator/qemu/linux-x86_64

      - name: Add Emulator to Path
        run: |
          export PATH=$PATH:/usr/local/lib/android/sdk/emulator

      - name: Initialize android emulator
        env:
          AVD_NAME: "TestAVD"
          API_LEVEL: 36
        run: | 
          chmod +x ./scripts/create-android-emu.sh
          ./scripts/create-android-emu.sh

      - name: SANITY CHECK FOR AVD
        run: |
          avdmanager list avd
          ls ${{ github.workspace }}/.android/avd

      - name: Start the Android Emulator
        run: |
          # -no-window and -no-audio reduce external dependency requirements
          /usr/local/lib/android/sdk/emulator/emulator -avd TestAVD -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect &

      - name: run firebase emulators and integrated tests
        run: |
          firebase emulators:exec --project ${{ secrets.FIREBASE_PROJECT_ID }} "./gradlew connectedAndroidTest"

